import Head from "next/head";
import Nav from "../components/nav";
import WorksSection from "../components/section/works/works";

import { data } from "@/data/data";
import Lenis from "lenis";
import { useEffect, useRef } from "react";

const Works = () => {
  const lenisRef = useRef(null);
  useEffect(() => {
    const lenis = new Lenis({
      autoRaf: true,
      duration: 1,
    });

    lenisRef.current = lenis;
    return () => lenis.destroy();
  }, []);
  return (
    <>
      <Head>
        <title>REVIVAL® - WORKS</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Nav />
      <main ref={lenisRef} className="min-h-screen">
        <WorksSection data={data} />
      </main>
    </>
  );
};

export default Works;
