"use client";

import HeroSection from "./components/section/home/hero";
import Nav from "./components/nav";

import Head from "next/head";

const HomePage = () => {
  return (
    <>
      <Head>
        <title>REVIVAL®</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Nav />
      <main className="min-h-screen">
        <HeroSection />
      </main>
    </>
  );
};

export default HomePage;
